### ISSUE TITLE
Using the surgery machine on level 2 crashes the engine

### ISSUE THREAD

**Issue by farmboy0** [Interrupt/systemshock#89]
Running it under gdb on use of the surgery machine there is a message that the machine is broken.

I am attaching a savegame right before it.

[save.zip](https://github.com/Interrupt/systemshock/files/2174031/save.zip)

**Comment by mrikola** [comment]
Please explain a bit more. 

The surgery machine is supposed to be broken and unfixable. Do you get an actual crash when using it, as the issue title suggests, or just the text "The machine is broken" which is the expected behavior?

**Comment by farmboy0** [comment]
When running the engine I get a crash.
When running the engine with gdb I get the expected behaviour (in game message that the machine is broken)

**Comment by Interrupt** [comment]
That's super weird, it doesn't crash there for me. Is there any log output during that?

**Comment by farmboy0** [comment]
Nope none, unfortunately.

**Comment by farmboy0** [comment]
Could this be timing related? What exactly doe the dopple click on the surgery machine trigger in the engine?

**Comment by Interrupt** [comment]
It probably triggers a trigger / trap sequence that then heals the player, or displays a message.

**Comment by inguin** [comment]
Works for me.

@farmboy0 Please run cmake with `-DCMAKE_BUILD_TYPE=Debug`, build, start in gdb and type `bt` after the crash to get a backtrace.

**Comment by farmboy0** [comment]
It doesnt crash in gdb like I said already.

**Comment by inguin** [comment]
Sorry, misunderstanding: I thought you saw the "machine is broken" message somewhere in the gdb console.

**Comment by inguin** [comment]
OK, I can reproduce the crash without gdb. Backtrace from core dump:

```
#0  0x080d9545 in do_multi_stuff (id=24832) at /home/inva/Coding/git/systemshock/src/GameSrc/trigger.c:1761
#1  0x080bb8ec in object_use (id=548, in_inv=0 '\000', cursor_obj=0)
    at /home/inva/Coding/git/systemshock/src/GameSrc/objuse.c:1079
#2  0x0808c92a in use_object_in_3d (obj=548) at /home/inva/Coding/git/systemshock/src/GameSrc/input.c:1917
#3  0x0808d3ca in view3d_dclick (pos=..., fr=0x0) at /home/inva/Coding/git/systemshock/src/GameSrc/input.c:2132
#4  0x0808d81b in view3d_mouse_handler (ev=0xffa85bea, r=0x81dcc00 <mv_region_data>, data=0x9ad7200)
    at /home/inva/Coding/git/systemshock/src/GameSrc/input.c:2269
#5  0x0810e939 in event_dispatch_callback (reg=0x81dcc00 <mv_region_data>, rect=0xffa85b56, v=0xffa85bea)
    at /home/inva/Coding/git/systemshock/src/Libraries/UI/Source/event.c:410
#6  0x0810ea4b in ui_try_region (reg=0x81dcc00 <mv_region_data>, pos=..., ev=0xffa85bea)
    at /home/inva/Coding/git/systemshock/src/Libraries/UI/Source/event.c:451
#7  0x0810eb95 in ui_traverse_point (reg=0x81dcc00 <mv_region_data>, pos=..., data=0xffa85bea)
    at /home/inva/Coding/git/systemshock/src/Libraries/UI/Source/event.c:484
#8  0x0810eb56 in ui_traverse_point (reg=0x81dcba0 <root_region_data>, pos=..., data=0xffa85bea)
    at /home/inva/Coding/git/systemshock/src/Libraries/UI/Source/event.c:478
#9  0x0810ecea in uiDispatchEventToRegion (ev=0xffa85cc6, reg=0x81dcba0 <root_region_data>)
    at /home/inva/Coding/git/systemshock/src/Libraries/UI/Source/event.c:514
#10 0x0810ed6b in uiDispatchEvent (ev=0xffa85cc6)
    at /home/inva/Coding/git/systemshock/src/Libraries/UI/Source/event.c:527
#11 0x0810f3f9 in ui_dispatch_mouse_event (mout=0xffa85cc6)
    at /home/inva/Coding/git/systemshock/src/Libraries/UI/Source/event.c:681
#12 0x0810f7ab in uiPoll () at /home/inva/Coding/git/systemshock/src/Libraries/UI/Source/event.c:900
#13 0x0808ac13 in input_chk () at /home/inva/Coding/git/systemshock/src/GameSrc/input.c:389
#14 0x08095aa8 in mainloop (argc=1, argv=0xffa85de4) at /home/inva/Coding/git/systemshock/src/GameSrc/mainloop.c:126
#15 0x080787f9 in main (argc=1, argv=0xffa85de4) at /home/inva/Coding/git/systemshock/src/MacSrc/Shock.c:163
```
